// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XiangXunBlog.Data;

#nullable disable

namespace XiangXunBlog.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XiangXunBlog.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("x_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Created = new DateTime(2025, 11, 16, 6, 22, 17, 662, DateTimeKind.Utc).AddTicks(2498),
                            Description = "与编程相关的文章",
                            Name = "编程"
                        });
                });

            modelBuilder.Entity("XiangXunBlog.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("x_posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AuthorId = "1",
                            CategoryId = "1",
                            Content = "这是您的第一篇文章。编辑或删除它，然后开始写作吧！",
                            Created = new DateTime(2025, 11, 16, 6, 22, 17, 662, DateTimeKind.Utc).AddTicks(2516),
                            LastUpdated = new DateTime(2025, 11, 16, 6, 22, 17, 662, DateTimeKind.Utc).AddTicks(2516),
                            Title = "欢迎来到XiangXunBlog"
                        });
                });

            modelBuilder.Entity("XiangXunBlog.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("x_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            PasswordHash = "123",
                            UserName = "xiangxun"
                        });
                });

            modelBuilder.Entity("XiangXunBlog.Models.Post", b =>
                {
                    b.HasOne("XiangXunBlog.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XiangXunBlog.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("XiangXunBlog.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
